name = "vuudra-search"
main = "src/index.js"
compatibility_date = "2023-12-01"

[build]
command = "npm run build"
watch_dir = "src"

[site]
bucket = "./dist"

[env.production]
name = "vuudra-search"
route = ""

[env.staging]
name = "vuudra-search-staging"

[triggers]
crons = []

[vars]
# Environment variables to be set
# EXAMPLE_VAR = "example_value"
