name: Build and publish

on:
  push:
    branches:
      - "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Clean dependency cache
        run: |
          echo "Removing any lockfiles to ensure fresh installation"
          rm -f package-lock.json pnpm-lock.yaml yarn.lock bun.lockb

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies and build locally first
        run: |
          bun install
          bun run build || echo "Local build failed, but continuing to Docker build"

      - name: Build and publish Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: Search
          image-tag: latest
          dockerfile: Dockerfile
